[package]
name = "clippy-relm"
version = "0.1.0"
authors = ["Julian Konchunas <konchunas@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "0.5.0"
relm = "0.15.2"
relm-derive = "0.15.2"
relm-attributes = "0.15.2"
